export const LOCAL_CACHE_KEYS = {
  AUTH: {
    IS_REMEBER_ME: 'AUTH.IS_REMEBER_ME',
    TOKEN: 'AUTH.TOKEN',
    REFRESH_TOKEN: 'AUTH.REFRESH_TOKEN',
    SESSION_TOKEN: 'AUTH.SESSION_TOKEN',
  },
};
