export const AppConfigKeys = {
  UI_KEYS: {
    BRANDING: {
      LOGO_URL: 'UI.BRANDING.LOGO_URL',
      LOGO_DARK_URL: 'UI.BRANDING.LOGO_DARK_URL',
      LOGO_LIGHT_URL: 'UI.BRANDING.LOGO_LIGHT_URL',
      ICON_URL: 'UI.BRANDING.ICON_URL',
      ICON_DARK_URL: 'UI.BRANDING.ICON_DARK_URL',
      ICON_LIGHT_URL: 'UI.BRANDING.ICON_LIGHT_URL',
      APP_NAME: 'UI.BRANDING.APP_NAME',
      TAGLINE: 'UI.BRANDING.TAGLINE',
      COPYRIGHT: 'UI.BRANDING.COPYRIGHT',
    },
    APP: {
      VERSION: 'UI.APP.VERSION',
      BUILD_NUMBER: 'UI.APP.BUILD_NUMBER',
    },
  },
};
